on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build only'
        uses: shalzz/zola-deploy-action@v0.15.2
        env:
          BUILD_DIR: .
          # Token from insysnw-bot account
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@v0.15.2
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          # Token from insysnw-bot account
          TOKEN: ${{ secrets.TOKEN }}
